services:
  wordpress:
    image: wordpress:latest
    container_name: takayasiro-local-container
    ports:
      - "8080:80" # localhost:8080 でWordPressにアクセス
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: example_db
      WORDPRESS_DB_USER: example_user
      WORDPRESS_DB_PASSWORD: example_password
    volumes:
      - wordpress_data:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini # カスタムphp.iniをマウント
      - ./themes:/var/www/html/wp-content/themes # テーマディレクトリをマウント
    networks:
      - wordpress_network

  db:
    image: mariadb:latest # MySQLの代わりにMariaDBを使用
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: example_db
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_network

volumes:
  wordpress_data:
  db_data:

networks:
  wordpress_network:
    driver: bridge
